# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id_comp', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comp', models.CharField(max_length=100)),
                ('mac_comp', models.CharField(max_length=20, unique=True)),
                ('ip_comp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id_lab', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lab', models.CharField(max_length=100, unique=True)),
                ('ip1_lab', models.GenericIPAddressField()),
                ('ip2_lab', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Lab'),
        ),
    ]
