# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributive',
            fields=[
                ('id_dist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='career.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id_sta', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sta', models.CharField(max_length=6, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='distributive',
            name='sta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distributive.Stage'),
        ),
        migrations.AddField(
            model_name='distributive',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Subject'),
        ),
        migrations.AddField(
            model_name='distributive',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dist', to='teacher.Teacher'),
        ),
    ]
