# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id_exter', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('finish_session', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Computer')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guest.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id_inter', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('finish_session', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
                ('type_user', models.CharField(max_length=1)),
                ('id_user', models.BigIntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.Computer')),
            ],
        ),
    ]
