# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributive', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_sched', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1)),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='distributive.Distributive')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sched', to='lab.Lab')),
            ],
        ),
    ]
