# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_adm', models.CharField(max_length=10, unique=True)),
                ('names_adm', models.CharField(max_length=150)),
                ('email_adm', models.EmailField(max_length=100)),
                ('password_adm', models.CharField(max_length=200)),
                ('token_reset', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField()),
            ],
        ),
    ]
