# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='ci',
            field=models.CharField(default='123', max_length=10),
            preserve_default=False,
        ),
    ]
